//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacketBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacketBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches header for containing given text (header is first line in packet details).
        /// </summary>
        public static string STR_HeaderSearchTooltip {
            get {
                return ResourceManager.GetString("STR_HeaderSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in header ....
        /// </summary>
        public static string STR_HeaderSearchWatermark {
            get {
                return ResourceManager.GetString("STR_HeaderSearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string STR_Loaded {
            get {
                return ResourceManager.GetString("STR_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string STR_Loading {
            get {
                return ResourceManager.GetString("STR_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load sniff.
        /// </summary>
        public static string STR_LoadSniff {
            get {
                return ResourceManager.GetString("STR_LoadSniff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching is done checking if packet data contains given text.
        /// </summary>
        public static string STR_PacketContainsDesc {
            get {
                return ResourceManager.GetString("STR_PacketContainsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing view.
        /// </summary>
        public static string STR_PreparingView {
            get {
                return ResourceManager.GetString("STR_PreparingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching is done checking if packet matches given regex.
        /// </summary>
        public static string STR_RegexDesc {
            get {
                return ResourceManager.GetString("STR_RegexDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string STR_Search {
            get {
                return ResourceManager.GetString("STR_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching depends on search type:
        ///Simple contains - searching is done checking if packet contains given text
        ///Packet contains - searching is done checking if packet data contains given text
        ///Regex - searching is done checking if packet matches given regex.
        /// </summary>
        public static string STR_SearchTooltip {
            get {
                return ResourceManager.GetString("STR_SearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ....
        /// </summary>
        public static string STR_SearchWatermark {
            get {
                return ResourceManager.GetString("STR_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching is done checking if packet contains given text.
        /// </summary>
        public static string STR_SimpleContainsDesc {
            get {
                return ResourceManager.GetString("STR_SimpleContainsDesc", resourceCulture);
            }
        }
    }
}
